# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build_lint:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 

  push_image:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # build docker image
      - run:
          name: build docker image
          command: |
            apk add --update docker
            docker build --tag=udacity_capstone .
            docker image ls

      - run:
          name: push docker image
          command: |
            echo "Docker ID and Image: $DOCKER_PATH"
            docker login --username=nitinbhagwat --password=$DOCKER_PASSWORD
            docker tag udacity_capstone $DOCKER_PATH
            docker push $DOCKER_PATH



workflows:
  capstone:
    jobs:
      - build_lint
      - push_image:
          requires: [build_lint]

